### ISSUE TITLE
TerraformPlan API is throwing status code 500 error without any message.

### ISSUE THREAD

**Issue by sandeep99063** [OpsMx/Terraform-spinnaker#2]
I have followed this doc to setup terraform and spinnaker on my local. https://docs.opsmx.com/codelabs/terraform-with-spinnaker/
But when I try to execute my terraform plan stage passing these as a parameter from UI

"{\n   \"gitAccount\": \"github-for-terraform\",\n   \"cloudAccount\": \"kubernetes\",\n   \"applicationName\": \"terraform-deployment-application\",\n   \"pipelineName\": \"Deploy using Terraform\",\n   \"pipelineId\": \"6affaae3-4e59-4141-913a-4b3c91669ec1\",   \n   \"plan\": \"TerraformPlanModule.git//openshot.tf\"\n}"

I am getting the following errors :

{
  "timestamp": "2019-12-26T11:13:36.586+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "No message available",
  "path": "/api/v1/terraformPlan"
}
Webhook failed: error submitting webhook for pipeline 01DXAYB7JJAVS83KFEDX08FTCY to http://10.106.113.217:8090/api/v1/terraformPlan, will retry.

Additional Details: I tested separately for the custom webhooks creation in my spinnaker setup and it worked fine.

Please help to find out, what is going wrong here?

Thanks in advance!

**Comment by markyjackson-taulia** [comment]
@sandeep99063 I have tried this and could not duplicate this. Can you give some insight into your environment?

**Comment by markyjackson-taulia** [comment]
Going to close this out. If you determine it needs more discussion, just ping me on the community spinnaker slack or kindly open a new issue.
